{
 "title": "Pomodoro Application dashboard",
 "tags": [
  "Pomodoro",
  "node.js"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "App Metrics - Total http requests",
   "type": "stat",
   "description": "Total no.of http requests",
   "gridPos": { "h": 5, "w": 20, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (route) (pomodoro_http_requests_total{route!~\"^/(metrics|live|ready|health|favicon.ico?)$\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Break metrics - Short Breaks",
   "type": "stat",
   "description": "Total no.of short breaks taken by users",
   "gridPos": { "h": 4, "w": 5, "x": 1, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_short_break_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User Metrics - Active users",
   "type": "stat",
   "description": "Total no.of users active today",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Task Metrics - Tasks created",
   "type": "stat",
   "description": "Total no.of tasks created",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_tasks_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Task Metrics - Downloaded Reports",
   "type": "stat",
   "description": "Total no.of reports downloaded",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pomodoro_download_reports_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Break metrics - Long Breaks",
   "type": "stat",
   "description": "Total no.of long breaks taken by users",
   "gridPos": { "h": 4, "w": 5, "x": 1, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_long_break_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User Metrics - New Users",
   "type": "stat",
   "description": "Total no.of users",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_new_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Task Metrics - Tasks completed",
   "type": "stat",
   "description": "Total no.of tasks created",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_tasks_completed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App Metrics - Server errors",
   "type": "stat",
   "description": "Total no.of errors occurred on server-side",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cient Metrics - Client errors",
   "type": "stat",
   "description": "Total no.of errors occurred on client-side",
   "gridPos": { "h": 5, "w": 6, "x": 1, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_client_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Application Metrics - uptime()",
   "type": "stat",
   "description": "The amount of time the application has been running since it was started.",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_app_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Application Metrics - cpu usage (microsec)",
   "type": "stat",
   "description": "The amount of CPU time used by the process. The object returned contains user and system properties, which represent the CPU time used by the user and system code, respectively.",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_cpu_usage_seconds" }
   ]
  },
  {
   "title": "Cient Metrics - Client app load time",
   "type": "timeseries",
   "description": "Total uptime on client-side",
   "gridPos": { "h": 6, "w": 11, "x": 1, "y": 18 },
   "targets": [
    {
     "expr": "pomodoro_client_page_load_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Metrics - memory usage",
   "type": "stat",
   "description": "The amount of memory used by the heap in the Node.js process.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pomodoro_memory_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App Metrics - Total http requests",
   "type": "timeseries",
   "description": "Total no.of http requests",
   "gridPos": { "h": 12, "w": 20, "x": 1, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route) (rate(pomodoro_http_request_duration_seconds_bucket{route!~\"/ready|/favicon.ico|/metrics|/live|/health\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Metrics - Total http requests",
   "type": "stat",
   "description": "Total no.of http requests",
   "gridPos": { "h": 7, "w": 20, "x": 1, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route) (rate(pomodoro_http_request_duration_seconds_bucket{route=~\"/live|/ready|/health\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Metrics - Total http requests",
   "type": "histogram",
   "description": "Total no.of http requests",
   "gridPos": { "h": 11, "w": 20, "x": 1, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pomodoro_database_query_duration_seconds_bucket",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}